version: '3.8'
services:
    nginx:
        #    image: 283158/vue-app-nginx
        build:
            context: ./web
        stdin_open: true
        tty: true
        ports:
            - '90:80'
        environment:
            - VUE_APP_BASE_URL=localhost:8000
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            -   "8077:80"
        environment:
            - PMA_HOST=db
            - MYSQL_USERNAME:root
            - MYSQL_ROOT_PASSWORD:@root
        depends_on:
            -   db
        networks:
            - app-network
    db:
        container_name: chat_db
        hostname: db
        image: 'mysql:8.0'
        environment:
            - MYSQL_DATABASE=chatDB
            - MYSQL_ROOT_PASSWORD=@root
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=@root
            - DATABASE_HOST=db
            - LC_ALL=C.UTF-8
            - LANG=C.UTF-8
        ports:
            - "3307:3306"
        volumes:
            - mysql:/var/lib/mysql
#            - ./data:/var/lib/mysql
            - ./server/sql:/docker-entrypoint-initdb.d
        networks:
            - app-network
    go-server:
        depends_on:
            - db
        build:
            context: ./server
        container_name: go-server
        hostname: go-server
        ports:
            - "8000:8080"
        restart: always
        networks:
            - app-network
        image: golang
        volumes:
            -   go-image:/app/server/uploads
        links:
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_NAME=chatDB
            - DB_USER=root
            - DB_PASS=@root

volumes:
    mysql:
    go-image:
networks:
    app-network:
        driver: bridge


